version: '3.8'

services:
  backend:
    image: python:3.9
    environment:
      - DB_HOST=${rds_endpoint}
    ports:
      - "8000:8000"
    command: >
          sh -c "python manage.py migrate &&
                python manage.py dumpdata --database=sqlite --natural-foreign --natural-primary -e contenttypes -e auth.Permission --indent 4 > datadump.json &&
                python manage.py loaddata datadump.json &&
                rm -f db.sqlite3 &&
                python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: node:14
    ports:
      - "3000:3000"
    depends_on:
      - backend
